### PR TITLE
Fix PlayerCollision Leak on client also

### PR DESCRIPTION
**Pull request by gameusefly**

### CODE REVIEW

**Comment by AymericBdy** [comment]
If you want to fix the fact that, when the client leaves a world/server, it isn't removed from the PhysicsWorld, it isn't a problem since the world is unloaded, and cleared.

**Comment by gameusefly** [comment]
When a another player leaves a world/server, on other clients there are still in the physics world. In my commit i fixxed that :)

**Comment by AymericBdy** [comment]
Ah yes, you're right :)
I think you can move the listener to the "fr.dynamx.common.handlers" package.
And to limit the new code, you can remove the LISTENER constant, and remove the call to world.removeEventListener since the world is unloaded so the listener won't be triggered again.

**Comment by gameusefly** [comment]
done

**Comment by AymericBdy** [comment]
Thanks for your PR ;)

**Pull request merged**
