### PR TITLE
Beta

### PR DESCRIPTION
**Pull request by JarException**
a few changes that improve performance when there are a lot of physics objects in the world

### CODE REVIEW

**Comment by AymericBdy** [comment]
For the physics contains check, we don't see how this would improve the performance compared to the existing code ?

**Comment by JarException** [comment]
The contains method of a list uses "O(n)" to check the list and the containsKey method of a HashMap works with "O(1)". Furthermore the method "getRigidBodyList" creates the list first and iterates 2x over the complete list of objects.

**Comment by AymericBdy** [comment]
You're right (but the creation of the unmodifiable list doesn't iterate over it).
I think using `dynamicsWorld.contains((PhysicsCollisionObject) object)` instead of the reflection would be better.

**Comment by JarException** [comment]
Yes, I must have described it a bit wrong. It doesn't iterate over the list, but it's very performance heavy to create it this way and then iterate over it again. if `dynamicsWorld.contains((PhysicsCollisionObject) object)` is really more performant than the single query with reflection i can't say at the current state. would have to test again. but the current version is definitely a very big improvement in performance when 50'000+ objects are in the list.

**Comment by AymericBdy** [comment]
Yes, your version is far better than using the list. 
I think the solution with `dynamicsWorld.contains((PhysicsCollisionObject) object)` is better than with reflection (easier to read, with less code), and the difference in execution time shouldn't be large, but in the right direction.
Feel free to measure it ;)

**Comment by JarException** [comment]
I have changed the method again in the latest commit, as you suggested

**Pull request merged**
