### PR TITLE
fix: power of a helicopter can only be changed when the engine is on

### PR DESCRIPTION
**Pull request by JarException**
a small fix. i don't think it's intentional that you can increase the power on a motor that hasn't been started. precisely because the power is reset to 0 when the motor is switched off.

### CODE REVIEW

**Comment by AymericBdy** [comment]
Good idea, but it would be better if it's done in the HelicopterController, in the if condition before calling "engine.setPower(...)", because setPower(...) should act as a normal setter, and somebody or an addon want to do something, it can, and the logic should be checked before.

**Comment by JarException** [comment]
I agree with you have changed it

**Comment by AymericBdy** [comment]
You will say I'm demanding, but it's better if you merge the two if in one line : if(key.pressed && engineStarted), if simplifies the code 😄

**Comment by JarException** [comment]
edits are allowed😠...
is changed 😆

**Comment by AymericBdy** [comment]
Perfect ! 😅

**Pull request merged**
